
This format will render correctly as HTML with syntax highlighting.

---

### Step 2: Link Examples in MkDocs Navigation

Next, configure `mkdocs.yml` to add the examples to your navigation bar. You can create a dedicated section for these examples, making it easy to add new ones as your project grows.

#### `mkdocs.yml` Configuration

Add each example file to the navigation in `mkdocs.yml` under an "Examples" or "Tutorials" section:

```yaml
site_name: TermXtract Documentation

theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [termxtract]

nav:
  - Home: index.md
  - API Reference:
      - TermExtractor: "::: termxtract.term_extractor.TermExtractor"
  - Examples:
      - TF-IDF Example: examples/tfidf_example.md
      # Add other method examples here as you expand, e.g.:
      # - RAKE Example: examples/rake_example.md
