site_name: TermXtract

theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [termxtract]

nav:
  - Home: index.md
  - TFIDFTermExtractor: docs/code/code1.md
  - Getting Started:
      - Overview: tutorials/getting_started.md
      - TF-IDF Tutorial: tutorials/tfidf_tutorial.md
      # Additional methods can be added here as new tutorials

