name: CI/CD Pipeline for Project TermXtract
on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to main
  workflow_dispatch:  # Allows manual triggers from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      # Step 3: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev

      # Step 4: Run project tests using unittest
      - name: Run Tests
        run: |
          poetry run python -m unittest discover tests

      # Step 5: Build MkDocs Site
      - name: Build MkDocs Site
        if: success()
        run: |
          poetry run mkdocs build

      # Step 6: Upload MkDocs Site for GitHub Pages Deployment
      - name: Upload to GitHub Pages
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v1
