name: CI/CD Pipeline for TermXtract

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to main
  workflow_dispatch:  # Allows manual triggers from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # Step 3: Install dependencies using Poetry and MkDocs
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          pip install mkdocs-material  # Ensure MkDocs and the Material theme are installed

      # Step 4: Run project tests using unittest
      - name: Run Tests
        run: |
          python -m unittest discover tests

      # Step 5: Build and Deploy MkDocs Site
      - name: Deploy to GitHub Pages
        if: success()  # Deploy only if all previous steps pass
        run: mkdocs gh-deploy --force

